version: '3'
services:
  postgres:
    image: arm64v8/postgres:13-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rs_pg_pubsub_dev
